name: auto_update

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: execute python script
        run: python update.py

      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add lista_del_lupo.txt
          git commit -m "update data" || exit 0
          git push
          
