name: Aggiornamento Lista del Lupo

on:
  schedule:
    # Gira ogni 3 giorni a mezzanotte (00:00) UTC
    - cron: '0 0 */3 * *'
  workflow_dispatch: # Ti permette di avviarlo anche a mano quando vuoi

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Controlla il codice del repository
      uses: actions/checkout@v3

    - name: Imposta Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Esegui lo script del Lupo
      run: python update.py

    - name: Salva le modifiche su GitHub
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add lista_del_lupo.txt
        git diff --quiet && git diff --staged --quiet || (git commit -m "Aggiornamento automatico della lista (Ogni 3 giorni)" && git push)
        
