name: Aggiornamento Automatico Lista del Lupo

on:
  workflow_dispatch: # Ti permette di farlo partire ancora a mano quando vuoi
  schedule:
    # Si attiva automaticamente ogni giorno alle 02:00 UTC (le 03:00 in Italia)
    - cron: '0 2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Accedi al codice
        uses: actions/checkout@v3

      - name: Configura Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Installa i componenti necessari
        run: pip install requests beautifulsoup4

      - name: Avvia lo Scanner Supremo
        run: python update.py

      - name: Salva le modifiche sulla lista
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add lista_del_lupo.txt
          git commit -m "Aggiornamento automatico della lista (LupoBot)" || exit 0
          git push
          
